version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
