version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/src/scripts"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
