version: "3"

vars:
  SRC_DIR: "{{.USER_WORKING_DIR}}/packages/cli"
  TOOLS_DIR: "{{.USER_WORKING_DIR}}/packages/tools"
  BIN_DIR: "{{.USER_WORKING_DIR}}/bin"

tasks:

  tidy:
    deps: [install-devtools]
    cmds:
      - "cd {{.SRC_DIR}} && go mod tidy -v"
      - "cd {{.SRC_DIR}} &&  gofmt -l -s -w {{.SRC_DIR}}"
      - "cd {{.TOOLS_DIR}} && go mod tidy -v"
      - "cd {{.TOOLS_DIR}} &&  gofmt -l -s -w {{.TOOLS_DIR}}"
      - '{{.BIN_DIR}}/gosimports -local "github.com/CircleCI-Public/slack-orb-go" -w {{.SRC_DIR}}'
      - go work sync
  
  update-deps:
    deps: [install-devtools]
    cmds:
      - "cd {{.SRC_DIR}} && go get -u ./..."
      - "cd {{.SRC_DIR}} && go mod tidy -v"
      - "cd {{.TOOLS_DIR}} && go get -u ./..."
      - "cd {{.TOOLS_DIR}} && go mod tidy -v"
  
  sync:
    deps: [install-devtools]
    cmds:
      - go work sync

  lint:
    deps: [install-devtools]
    cmd: "{{.BIN_DIR}}/golangci-lint run {{.SRC_DIR}}"

  test:
    cmd: go test -count=1 {{.SRC_DIR}}/...

  clean:
    cmd: go clean -modcache -x

  install-devtools:
    silent: true
    cmd: |
      tools=()
      while IFS='' read -r value; do
        tools+=("$value")
      done < <(grep _ {{.TOOLS_DIR}}/tools.go | awk -F'"' '{print $2}')

      for pkg in "${tools[@]}"; do
        #echo "Installing ${pkg}"
        (
          cd {{.TOOLS_DIR}}
          GOBIN="{{.BIN_DIR}}" go install "${pkg}" > /dev/null 2>&1
        )
      done
